# Generated by Django 5.1.6 on 2025-02-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(blank=True, max_length=50, null=True)),
                ('AdID', models.IntegerField(blank=True, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
