# Generated by Django 5.1.6 on 2025-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_bookingdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
