# Generated by Django 5.1.6 on 2025-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_bookingdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
