# Generated by Django 5.1.6 on 2025-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_bookingdb_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Note', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('AdID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
