# Generated by Django 5.1.6 on 2025-02-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='BookingID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
