# Generated by Django 5.1.6 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_orderdb_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='UserName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
