# Generated by Django 5.1.6 on 2025-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_orderdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AdID', models.CharField(max_length=50)),
                ('BookingID', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
