# Generated by Django 5.1.6 on 2025-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_orderdb_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('AdID', models.CharField(max_length=50)),
                ('ClientName', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
