# Generated by Django 5.1.6 on 2025-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_reviewdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
