# Generated by Django 5.1.6 on 2025-02-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_reviewdb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='UserName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
