# Generated by Django 5.1.6 on 2025-02-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_reviewdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
