# Generated by Django 5.1.6 on 2025-02-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_reviewdb_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdb',
            old_name='color',
            new_name='Color',
        ),
    ]
