# Generated by Django 5.1.6 on 2025-02-18 07:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0015_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterModelOptions(
            name='bookingdb',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='AdID',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='ClientName',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='UserName',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='booking_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='property_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
