# Generated by Django 5.1.6 on 2025-02-18 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0016_delete_booking_alter_bookingdb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPaymentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('property_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingdb',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='AdID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='ClientName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='UserName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
