# Generated by Django 5.1.6 on 2025-02-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_postdb_information_postdb_kitchen_postdb_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='postdb',
            name='Name',
        ),
    ]
