# Generated by Django 5.1.6 on 2025-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_postdb_description_remove_postdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='Mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
