# Generated by Django 5.1.6 on 2025-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_postdb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
