# Generated by Django 5.1.6 on 2025-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_postdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
